"""initial

Revision ID: 013a1fbd53b6
Revises: 2a608084359b
Create Date: 2024-05-07 20:43:20.872802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013a1fbd53b6'
down_revision: Union[str, None] = '2a608084359b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('grade_date', sa.Date(), nullable=True))
    op.drop_column('grades', 'date_of')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('date_of', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('grades', 'grade_date')
    # ### end Alembic commands ###
