"""initial

Revision ID: be6ea2fa5044
Revises: 013a1fbd53b6
Create Date: 2024-05-07 20:47:34.206346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6ea2fa5044'
down_revision: Union[str, None] = '013a1fbd53b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('students', 'fullname',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=175),
               existing_nullable=False)
    op.alter_column('teachers', 'fullname',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'fullname',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('subjects', 'name',
               existing_type=sa.String(length=175),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('students', 'fullname',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
